---

# ------------------------------------------------------------------------
# UPDATE SOFTWARE AND INSTALL PACKAGES NEEDED
# ------------------------------------------------------------------------

- name: Update system software
  yum: name=* state=latest

- name: "Install oddjob-mkhomedir, oddjob, and authconfig"
  yum: name={{ item }} state=latest
  with_items:
    - oddjob-mkhomedir
    - oddjob
    - authconfig

# ------------------------------------------------------------------------
# CONFIGURE THE ODDJOB DAEMON SERVICE
# ------------------------------------------------------------------------

- name: Enable the oddjob daemon to run on boot
  service: name=oddjobd enabled=yes

- name: Start the oddjob daemon
  service: name=oddjobd state=started
  register: oddjobd_result
  ignore_errors: yes

- name: Restart the messagebus if we couldn't start the oddjob daemon
  service: name=messagebus state=restarted
  when: oddjobd_result | failed

- name: Try to start the oddjob daemon again if we couldn't the first time
  service: name=oddjobd state=started
  when: oddjobd_result | failed

# ------------------------------------------------------------------------
# USE AUTHCONFIG TO MAKE ODDJOBD CREATE DIRECTORY UPON LOGIN
# ------------------------------------------------------------------------

- name: "Ensure that the metadata directory used for idempotence is created"
  file: 
    path: "{{ ansible_env.HOME }}/{{ playbook_metadata_dir }}"
    state: directory

- name: "Ensure that that metadata file for mkhomedir is present"
  file:
    path: "{{ playbook_metadata_dir }}/mkhomedir_authconfig"
    state: touch

- name: "Check if authconfig has been used to enable a home directory to be made upon login"
  command: /bin/bash -c "/bin/cat {{ playbook_metadata_dir }}/mkhomedir_authconfig"
  register: mkhomedir_metadata
  always_run: yes
  changed_when: no

- name: Update authentication mechanism to tell oddjob to create the directory automatically upon login
  command: /usr/sbin/authconfig --enablemkhomedir --update
  when: "'success' in mkhomedir_metadata.stdout"

- name: "Register the metadata file for mkhomedir"
  lineinfile:
    dest: "{{ playbook_metadata_dir }}/mkhomedir_authconfig"
    regexp: "^success"
    line: "success"