---

# ------------------------------------------------------------------------
# MKHOMEDIR DEFAULT VARIABLES
# ------------------------------------------------------------------------

mkhomedir_metadata_string: "success"